### ISSUE TITLE
Ability to override the banner logo

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-io/spring-asciidoctor-backends#24]
I am investigating if I could use this project to document my https://github.com/wimdeblauwe/error-handling-spring-boot-starter library. It has quite some nice improvements over the default Asciidoctor stack. 

I got it working by adding the milestone repo as plugin repo:

```
    <pluginRepositories>
        <pluginRepository>
            <id>spring-milestone</id>
            <name>Spring Milestone Repository</name>
            <url>https://repo.spring.io/milestone</url>
        </pluginRepository>
    </pluginRepositories>
```

One thing I would need is that I can override the `banner-logo.svg` (or just remove it) so people don't think my library is an official Spring one. Maybe also the `doc-background.svg`? Maybe it can be made configurable via an Asciidoc attribute?

**Comment by philwebb** [comment]
I think the banner-logo definition is currently in css so you might be able to override it by providing an additional css file. We can certainly look into making things more configurable, but it might take a little while for us to get to that since the initial goal of the project is just to make our own documentation better.

**Comment by wimdeblauwe** [comment]
No problem. I managed to work around it for now by excluding the images from being published:

```
      - name: GitHub Pages action
        if: |
          github.ref == 'refs/heads/master' &&
           matrix.java == 8
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/generated-docs
          exclude_assets: 'img/banner-logo.svg,img/doc-background.svg,img/doc-background-dark.svg'
```

You can view the result at https://wimdeblauwe.github.io/error-handling-spring-boot-starter/

**Comment by ciscoo** [comment]
I was able to override with by defining a [`docinfo.html`](https://docs.asciidoctor.org/asciidoctor/latest/docinfo/):

`src/main/docs/asciidoc/docinfo.html`
```html
<link href="css/custom.css" rel="stylesheet">
```

The CCS:

`src/main/docs/asciidoc/css/custom.css`

```css
#banner {
    background-image: url("../img/custom-banner-light.svg");
}

html.dark-theme #banner {
    background-image: url("../img/custom-banner-dark.svg");
}

#doc {
    background-image: url("../img/custom-header-doc.svg");
}

html.dark-theme #doc {
    background-image: url("../img/custom-header-doc-dark.svg");
}

@media screen and (max-width: 800px) {
    html.dark-theme #doc,
    #doc {
        background: none;
    }
}
```

and update task to include the custom resources:

```kotlin
tasks {
    asciidoctor {
        resources {
            from(sourceDir) {
                include("css/**", "img/**")
            }
        }
    }
}
```
